// Turn a finished roundtable into a decision record.
//
// This is the artefact the debate exists to produce. A transcript on a screen
// is entertainment; a file you can commit next to the code is the thing that
// stops the same argument being had again in three months. The format follows
// the shape of an ADR deliberately — context, decision, dissent — so it drops
// into an existing docs/adr or an Obsidian vault without reformatting.
//
// Dissent is a first-class section rather than a footnote. The whole reason to
// run five specialists instead of one is to find out what the winning answer
// costs, and that information lives entirely in what the losers still believe.

const PHASE_LABEL = {
  brief: 'Framing',
  opening: 'Opening positions',
  clash: 'Cross-examination',
  converge: 'Final positions',
  verdict: 'Verdict',
}

export function debateToMarkdown(d) {
  if (!d || typeof d !== 'object') return '# Roundtable\n\n_no such debate_\n'

  const turns = Array.isArray(d.turns) ? d.turns : []
  const at = ms => (ms ? new Date(ms).toISOString().replace('T', ' ').slice(0, 16) + ' UTC' : 'unknown')
  const verdict = turns.filter(t => t.phase === 'verdict' && !t.failed).pop()
  const finals = turns.filter(t => t.phase === 'converge' && !t.failed)
  const openings = turns.filter(t => t.phase === 'opening' && !t.failed)

  const out = []
  out.push(`# ${d.topic}`)
  out.push('')
  out.push(`> Roundtable \`${d.id}\` · ${d.roomLabel || 'workspace'} · ${at(d.startedAt)}`)
  out.push(`> Participants: ${(d.participants || []).join(', ') || '—'} · model \`${d.model}\` · cost $${Number(d.costUsd || 0).toFixed(3)}`)
  if (d.cancelled) out.push('> **Cancelled before conclusion — this record is partial.**')
  if (d.error) out.push(`> **Failed: ${d.error}**`)
  out.push('')

  if (verdict) {
    out.push('## Decision')
    out.push('')
    out.push(verdict.body || '_no verdict recorded_')
    out.push('')
  }

  // Movement is the evidence the debate did work. A participant whose
  // confidence never moved either was right from the start or never engaged,
  // and the reader deserves to see which by comparing the two columns.
  const moved = movement(openings, finals)
  if (moved.length) {
    out.push('## Movement')
    out.push('')
    out.push('| Participant | Opening | Final | Confidence | Conceded |')
    out.push('|---|---|---|---|---|')
    for (const m of moved) {
      out.push(`| ${m.name} (${m.role}) | ${cell(m.opening)} | ${cell(m.final)} | ${m.shift} | ${m.conceded ? 'yes' : 'no'} |`)
    }
    out.push('')
  }

  // Not "surviving dissent": a participant who did not concede has not
  // necessarily dissented — the room can converge on one answer from three
  // different directions, and labelling that agreement as dissent misreports
  // the debate. Whether real dissent survived is a judgement the moderator
  // makes in the verdict above; this section reports the raw landing spots.
  if (finals.length) {
    out.push('## Where each specialist landed')
    out.push('')
    for (const t of finals) {
      const flag = t.conceded ? ' — **conceded**' : ''
      out.push(`**${t.speakerName} — ${t.speakerRole}** (confidence ${t.confidence ?? '?'})${flag}`)
      out.push('')
      out.push(`${t.position || ''}`.trim())
      out.push('')
      out.push(`${t.body || ''}`.trim())
      out.push('')
    }
  }

  out.push('## Full transcript')
  out.push('')
  for (const phase of ['brief', 'opening', 'clash', 'converge', 'verdict']) {
    const list = turns.filter(t => t.phase === phase)
    if (!list.length) continue
    out.push(`### ${PHASE_LABEL[phase]}`)
    out.push('')
    for (const t of list) {
      const flags = [
        t.conceded ? 'conceded' : null,
        t.confidence != null ? `confidence ${t.confidence}` : null,
        t.failed ? 'FAILED' : null,
      ].filter(Boolean).join(' · ')
      out.push(`**${t.speakerName}**${flags ? ` _(${flags})_` : ''}`)
      out.push('')
      if (t.position) out.push(`*${t.position}*`)
      out.push('')
      out.push(`${t.body || ''}`.trim())
      out.push('')
    }
  }

  out.push('---')
  out.push('')
  out.push('_Generated by Quorum — roundtable._')
  out.push('')
  return out.join('\n')
}

function movement(openings, finals) {
  const byId = new Map()
  for (const t of openings) byId.set(t.speaker, { name: t.speakerName, role: t.speakerRole, opening: t, final: null })
  for (const t of finals) {
    const row = byId.get(t.speaker) || { name: t.speakerName, role: t.speakerRole, opening: null, final: null }
    row.final = t
    byId.set(t.speaker, row)
  }
  return [...byId.values()].map(r => ({
    name: r.name,
    role: r.role,
    opening: r.opening?.position || '',
    final: r.final?.position || '',
    conceded: !!r.final?.conceded,
    shift: shiftLabel(r.opening?.confidence, r.final?.confidence),
  }))
}

function shiftLabel(a, b) {
  if (a == null || b == null) return '—'
  const d = b - a
  if (d === 0) return `${a} → ${b} (held)`
  return `${a} → ${b} (${d > 0 ? '+' : ''}${d})`
}

// Table cells cannot contain a raw pipe or newline without breaking the row.
const cell = s => String(s || '—').replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ').slice(0, 160)
