// Turn a finished roundtable into a decision record.
//
// This is the artefact the debate exists to produce. A transcript on a screen
// is entertainment; a file you can commit next to the code is the thing that
// stops the same argument being had again in three months. The format follows
// the shape of an ADR deliberately — context, decision, dissent — so it drops
// into an existing docs/adr or an Obsidian vault without reformatting.
//
// Dissent is a first-class section rather than a footnote. The whole reason to
// run five specialists instead of one is to find out what the winning answer
// costs, and that information lives entirely in what the losers still believe.

const PHASE_LABEL = {
  brief: 'Framing',
  opening: 'Opening positions',
  clash: 'Cross-examination',
  converge: 'Final positions',
  verdict: 'Verdict',
}

export function debateToMarkdown(d) {
  if (!d || typeof d !== 'object') return '# Roundtable\n\n_no such debate_\n'

  const turns = Array.isArray(d.turns) ? d.turns : []
  const at = ms => (ms ? new Date(ms).toISOString().replace('T', ' ').slice(0, 16) + ' UTC' : 'unknown')
  const verdict = turns.filter(t => t.phase === 'verdict' && !t.failed).pop()
  const finals = turns.filter(t => t.phase === 'converge' && !t.failed)
  const openings = turns.filter(t => t.phase === 'opening' && !t.failed)

  const out = []
  out.push(`# ${d.topic}`)
  out.push('')
  out.push(`> Roundtable \`${d.id}\` · ${d.roomLabel || 'workspace'} · ${at(d.startedAt)}`)
  out.push(`> Participants: ${(d.participants || []).join(', ') || '—'} · model \`${d.model}\` · cost $${Number(d.costUsd || 0).toFixed(3)}`)
  if (d.cancelled) out.push('> **Cancelled before conclusion — this record is partial.**')
  if (d.error) out.push(`> **Failed: ${d.error}**`)
  out.push('')

  if (verdict) {
    out.push('## Decision')
    out.push('')
    out.push(verdict.body || '_no verdict recorded_')
    out.push('')
  }

  // Movement is the evidence the debate did work. A participant whose
  // confidence never moved either was right from the start or never engaged,
  // and the reader deserves to see which by comparing the two columns.
  const moved = movement(openings, finals)
  if (moved.length) {
    out.push('## Movement')
    out.push('')
    out.push('| Participant | Opening | Final | Confidence | Conceded |')
    out.push('|---|---|---|---|---|')
    for (const m of moved) {
      out.push(`| ${m.name} (${m.role}) | ${cell(m.opening)} | ${cell(m.final)} | ${m.shift} | ${m.conceded ? 'yes' : 'no'} |`)
    }
    out.push('')
  }

  // Not "surviving dissent": a participant who did not concede has not
  // necessarily dissented — the room can converge on one answer from three
  // different directions, and labelling that agreement as dissent misreports
  // the debate. Whether real dissent survived is a judgement the moderator
  // makes in the verdict above; this section reports the raw landing spots.
  if (finals.length) {
    out.push('## Where each specialist landed')
    out.push('')
    for (const t of finals) {
      const flag = t.conceded ? ' — **conceded**' : ''
      out.push(`**${t.speakerName} — ${t.speakerRole}** (confidence ${t.confidence ?? '?'})${flag}`)
      out.push('')
      out.push(`${t.position || ''}`.trim())
      out.push('')
      out.push(`${t.body || ''}`.trim())
      out.push('')
    }
  }

  out.push('## Full transcript')
  out.push('')
  for (const phase of ['brief', 'opening', 'clash', 'converge', 'verdict']) {
    const list = turns.filter(t => t.phase === phase)
    if (!list.length) continue
    out.push(`### ${PHASE_LABEL[phase]}`)
    out.push('')
    for (const t of list) {
      const flags = [
        t.conceded ? 'conceded' : null,
        t.confidence != null ? `confidence ${t.confidence}` : null,
        t.failed ? 'FAILED' : null,
      ].filter(Boolean).join(' · ')
      out.push(`**${t.speakerName}**${flags ? ` _(${flags})_` : ''}`)
      out.push('')
      if (t.position) out.push(`*${t.position}*`)
      out.push('')
      out.push(`${t.body || ''}`.trim())
      out.push('')
    }
  }

  out.push('---')
  out.push('')
  out.push('_Generated by Quorum — roundtable._')
  out.push('')
  return out.join('\n')
}

/**
 * A self-contained, browser-friendly export for demos and review links. It
 * intentionally renders the same bounded debate fields as the markdown
 * record; persona prompts and credentials never enter the export surface.
 */
export function debateToHtml(d) {
  if (!d || typeof d !== 'object') return '<!doctype html><title>Quorum roundtable</title><p>No such debate.</p>'
  const turns = Array.isArray(d.turns) ? d.turns : []
  const verdict = turns.filter(t => t.phase === 'verdict' && !t.failed).pop()
  const finals = turns.filter(t => t.phase === 'converge' && !t.failed)
  const openings = turns.filter(t => t.phase === 'opening' && !t.failed)
  const rows = movement(openings, finals)
  const title = escapeHtml(d.topic || 'Roundtable')
  const status = d.cancelled ? '<p class="notice">Cancelled before conclusion — this record is partial.</p>'
    : d.error ? `<p class="notice">Failed: ${escapeHtml(d.error)}</p>` : ''
  const decision = verdict ? `<section class="decision"><p class="eyebrow">DECISION</p><h2>${escapeHtml(verdict.position || 'Recorded verdict')}</h2><p>${escapeHtml(verdict.body || '')}</p></section>` : ''
  const movementTable = rows.length ? `<section><p class="eyebrow">MOVEMENT</p><table><thead><tr><th>Participant</th><th>Opening</th><th>Final</th><th>Confidence</th><th>Conceded</th></tr></thead><tbody>${rows.map(row => `<tr><td>${escapeHtml(row.name)}<small>${escapeHtml(row.role)}</small></td><td>${escapeHtml(row.opening)}</td><td>${escapeHtml(row.final)}</td><td>${escapeHtml(row.shift)}</td><td>${row.conceded ? 'yes' : 'no'}</td></tr>`).join('')}</tbody></table></section>` : ''
  const landed = finals.length ? `<section><p class="eyebrow">WHERE EACH SPECIALIST LANDED</p>${finals.map(t => `<article class="specialist"><h3>${escapeHtml(t.speakerName)} <small>${escapeHtml(t.speakerRole)} · confidence ${escapeHtml(t.confidence ?? '?')}${t.conceded ? ' · conceded' : ''}</small></h3><p class="position">${escapeHtml(t.position || '')}</p><p>${escapeHtml(t.body || '')}</p></article>`).join('')}</section>` : ''
  const transcript = turns.length ? `<section><p class="eyebrow">FULL TRANSCRIPT</p>${turns.map(t => `<article class="turn ${t.failed ? 'failed' : ''}"><h3>${escapeHtml(t.speakerName)} <small>${escapeHtml(PHASE_LABEL[t.phase] || t.phase)}${t.confidence != null ? ` · confidence ${escapeHtml(t.confidence)}` : ''}${t.conceded ? ' · conceded' : ''}</small></h3>${t.position ? `<p class="position">${escapeHtml(t.position)}</p>` : ''}<p>${escapeHtml(t.body || '')}</p></article>`).join('')}</section>` : ''
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Quorum roundtable</title>
<style>:root{color-scheme:dark;--bg:#0b0d12;--panel:#121722;--line:#283142;--text:#e8edf5;--muted:#94a3b8;--accent:#f0b85c}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#1b2433 0,#0b0d12 42%);color:var(--text);font:15px/1.6 Inter,ui-sans-serif,system-ui,sans-serif}main{max-width:980px;margin:0 auto;padding:56px 24px 80px}header{border-bottom:1px solid var(--line);padding-bottom:28px}h1{font-size:clamp(28px,5vw,54px);line-height:1.05;margin:8px 0 18px;letter-spacing:-.04em}h2{font-size:26px;margin:0 0 10px}h3{font-size:16px;margin:0 0 8px}.eyebrow{color:var(--accent);font-size:11px;font-weight:700;letter-spacing:.16em;margin:0 0 12px}.meta,small{color:var(--muted);font-size:12px}.notice{border:1px solid #795d2b;background:#332817;padding:12px 16px;border-radius:10px}.decision,section{margin-top:30px}.decision{background:linear-gradient(135deg,#1b2432,#111722);border:1px solid #3b4659;border-left:3px solid var(--accent);padding:24px;border-radius:12px}.decision p:last-child{margin-bottom:0}.specialist,.turn{border-top:1px solid var(--line);padding:16px 0}.position{color:#f4ca83;font-weight:600;margin:0 0 4px}table{border-collapse:collapse;width:100%;background:rgba(18,23,34,.72);border:1px solid var(--line);border-radius:10px;overflow:hidden}th,td{text-align:left;padding:11px 13px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-size:11px;letter-spacing:.08em;text-transform:uppercase}td small{display:block}.failed{opacity:.65}.footer{color:var(--muted);border-top:1px solid var(--line);margin-top:44px;padding-top:18px;font-size:12px}</style></head>
<body><main><header><p class="eyebrow">QUORUM · ROUNDTABLE</p><h1>${title}</h1><p class="meta">${escapeHtml(d.roomLabel || 'workspace')} · ${(d.participants || []).length} seats · ${escapeHtml(d.model || 'unknown model')} · $${Number(d.costUsd || 0).toFixed(3)} · ${escapeHtml(formatTime(d.startedAt))}</p>${status}</header>${decision}${movementTable}${landed}${transcript}<p class="footer">Generated by Quorum. This export contains the decision record and transcript only; provider credentials and persona prompts are never included.</p></main></body></html>`
}

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]))
}

function formatTime(ms) {
  return ms ? new Date(ms).toISOString().replace('T', ' ').slice(0, 16) + ' UTC' : 'time unknown'
}

function movement(openings, finals) {
  const byId = new Map()
  for (const t of openings) byId.set(t.speaker, { name: t.speakerName, role: t.speakerRole, opening: t, final: null })
  for (const t of finals) {
    const row = byId.get(t.speaker) || { name: t.speakerName, role: t.speakerRole, opening: null, final: null }
    row.final = t
    byId.set(t.speaker, row)
  }
  return [...byId.values()].map(r => ({
    name: r.name,
    role: r.role,
    opening: r.opening?.position || '',
    final: r.final?.position || '',
    conceded: !!r.final?.conceded,
    shift: shiftLabel(r.opening?.confidence, r.final?.confidence),
  }))
}

function shiftLabel(a, b) {
  if (a == null || b == null) return '—'
  const d = b - a
  if (d === 0) return `${a} → ${b} (held)`
  return `${a} → ${b} (${d > 0 ? '+' : ''}${d})`
}

// Table cells cannot contain a raw pipe or newline without breaking the row.
const cell = s => String(s || '—').replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ').slice(0, 160)
